MLP:
    hidden_dim: 512
    hidden_depth: 5
    output_dim: 1
    dropout: 0
MLP_cond:
    hidden_dim: 1024
    hidden_depth: 3
    output_dim: 1
    dropout: 0.3
Unet_1d:
    down_dims: [256, 512, 1024]
MLP_Conv:
    hidden_dim: 1024
    hidden_depth: 3
    output_dim: 1
    dropout: 0.3
    hidden_channel: 16